# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72694b340398f96ff9854e1ca9b3e07662ae84ebdbfdcaff276a556bb74b01c43c30dff4161506ac03d0c6206fb0130b29c66ba29fa8020ca39fce51b90327df

test:
  secret_key_base: a6777ad48ade102113e9295e92f78782bb06d4ea9e6f2b484335362dbb13cd4395b624f6862257c9bf554e7c9edd3c7adce1c0ddb9121c3776b1de0b532b424b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
